### PR TITLE
Use @mixin instead of @extend

### PR DESCRIPTION
**Pull request by felics**
## New syntax:

```scss

.parent {
     // Declare grid with modifiers
    @include g(center, middle);
}

.child {
   // Declare grid-item with width / responsive widths
  @include i(1/2, lap 1/3, desk 1/4);

  // Include push/pull (same arg-syntax as i)
  @include push(desk 2/5);
}

```

## Contents:

 - Concise & precise new syntax
 - By default light wrapper around flexbox
 - Cleaner margin / padding-approach
 - Remove standalone version
 - Use DRYed mixins in favor of extends - much smarter and better traceable output css
 - Infinite columns / ratio-based
 - [Embrace the *-selector for some modifiers. Modern browsers can handle it well](http://blogs.telerik.com/kendoui/posts/12-09-28/css_tip_star_selector_not_that_bad)
 - Remove visibility-classes
 - 

## Todo:

- [x]  ~~Update Readme~~
- [x] ~~Write Tests~~
- [x] ~~Code Cleanup & Comments~~
- [ ] Crossbrowser Tests

### CODE REVIEW

**Comment by philippkuehn** [comment]
Hey, do you really dropped inline-block fallback?

**Comment by felics** [comment]
@philippkuehn

 Yes, I consider dropping it with the next release. Flexbox has pretty broad support nowadays, the only notable exceptions being IE9- & Android 4.3-. I'll probably include legacy-flexbox-syntax for Android 2.2+, so that leaves us with IE9- being the only browsers not to support flexbox. The user-data from my last few projects doesn't justify an inclusion, but I'm still monitoring that. The benefit of dropping it is a much cleaner & maintainable codebase. the `inline-block` grid used in this project was heavily influenced by [csswizardry-grids](https://github.com/csswizardry/csswizardry-grids) and yahoo's great [pure](http://purecss.io/grids/). That being said, I'm not 100% decided yet and it would be pretty easy to bring it back under a flag.

**Comment by felics** [comment]
@philippkuehn 

I added back the fallback-grid for the time being but disabled it by default. :)

**Comment by philippkuehn** [comment]
Yeah nice! At the moment i'm working with csswizardry-grids, but i need some flexbox features and can not drop old IE support :(
Your grid seems to be perfect next grid for me :)

**Comment by philippkuehn** [comment]
And one more question:
Why do I have to define `$hagrid-font` for the fallback? At csswizardry-grids there is no need for this.

**Comment by felics** [comment]
@philippkuehn 

[Reason](https://github.com/yahoo/pure/issues/41/) => [Solution](https://github.com/yahoo/pure/blob/master/src/grids/css/grids-core.css)

csswizardry-grids is a bit out of date in some aspects

**Comment by philippkuehn** [comment]
Ah yeah. I removed all whitespace between Html-Tags on my pages, so I don't have to use this hack. Would be nice, to have this as on option.

**Comment by felics** [comment]
You only have that problem in IE9 or Android 4.3-, flexbox removes the need for this everywhere else. I'll stick with the Yahoo-version as its the most reasonable approach imo, the HTML-trick is an overkill to do just for some legacy browsers.

**Comment by philippkuehn** [comment]
Yeah, I know. At the moment I have a really dynamic page, where you can control very much styling in the backend (including fonts etc.). So this could be a problem for me. But this is really an edge case. But it is a case :)

**Comment by felics** [comment]
Can you explain your problem in more details? I'm not sure if I get it

**Comment by philippkuehn** [comment]
I have to set $hagrid-font in sass. I compile on my local machine. At my site I have an additional css file only for font-styles, which is generated online. So at the moment I compile the grid, I have no idea, what font I am using at my site.

**Comment by felics** [comment]
@philippkuehn Added the option back in. QUickly tested it on IE9 via SauceLabs and it seems to work. :beers:

**Comment by philippkuehn** [comment]
Thanks dude! :+1:

**Pull request closed without merging**
